version: '3'
services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - 5432:5432
    expose:
      - 5432

  backend:
    build:
      context: ./strapi
      dockerfile: Dockerfile.dev
    ports:
      - 1337:1337
    depends_on:
      - db
    env_file: ./strapi/.env
    volumes:
      - ./strapi/config:/strapi-app/config
      - ./strapi/src:/strapi-app/src
      - ./strapi/package.json:/strapi-app/package.json
      - ./strapi/yarn.lock:/strapi-app/yarn.lock
      - ./strapi/.env:/strapi-app/.env
      - ./strapi/public:/strapi-app/public
    restart: unless-stopped

  frontend:
    build:
      context: ./nuxt
      dockerfile: Dockerfile.dev
    tmpfs: /tmp
    ports:
      - 3000:3000
      - 24678:24678
    depends_on:
      - backend
    env_file: ./nuxt/.env
    volumes:
      - ./nuxt:/nuxt-app
      - /nuxt-app/node_modules
    restart: unless-stopped
