# Use an official Node.js runtime as the base image
FROM node:18.18-alpine3.17

# Set the working directory in the container
WORKDIR /nuxt-app

# Update basics linux depedencies
RUN apk update && apk upgrade
RUN apk add git

# Specify dev env
ARG NODE_ENV=development
ENV NODE_ENV=${NODE_ENV}

# Copy the package.json and yarn.lock to the container
COPY package*.json yarn.lock .npmrc ./

# Install dependencies
RUN yarn install

# Copy the rest of the application code to the container
COPY . .

# Expose the port that the application will run on
EXPOSE 3000
EXPOSE 24678

# Start the application
CMD ["yarn", "dev"]
